server:
  port: 7000
spring:
  zipkin:
    base-url: http://127.0.0.1:9411/  #zipkin server的请求地址
    discoveryClientEnabled: false #让nacos把它当成一个URL，而不要当做服务名
  sleuth:
    sampler:
      probability: 1.0  #采样的百分比
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes: #路由数组【路由就是请求满足条件时转发到对应的微服务上】
        - id: product_route
#          uri: http://localhost:8081
          uri: lb://service-product
          order: 1
          predicates:
            - Path=/product-serv/**
#            - Age=18,60
          filters:
            - StripPrefix=1
#            - Log=true,false
        - id: order_route
            #          uri: http://localhost:8081
          uri: lb://service-order
          order: 1
          predicates:
            - Path=/order-serv/**
            #            - Age=18,60
          filters:
            - StripPrefix=1
        #            - Log=true,false

